[versions]
activity = "1.11.0"
androidGradlePlugin = "8.13.1"
coil = "3.3.0"
commonsCsv = "1.14.1"
compose = "1.9.4"
materialIconExtended = "1.7.8"
core = "1.7.0"
coreSplashscreen = "1.2.0"
coreTesting = "1.1.1"
datastore = "1.1.7"
fit = "21.176.0"
androidHilt = "1.3.0"
javaJwt = "4.5.0"
junit = "4.13.2"
junitAndroid = "1.3.0"
kotlinPlugin = "2.2.21"
kotlinxCoroutinesTest = "1.10.2"
kotlinxSerializationJson = "1.9.0"
ksp = "2.3.2"
lifecycle = "2.9.4"
material3 = "1.4.0"
mockk = "1.14.6"
navigationCompose = "2.9.6"
okhttp = "5.3.0"
okhttpSignpost = "1.1.0"
retrofit = "3.0.0"
roomVersion = "2.8.3"
truth = "1.4.5"
hilt = "2.57.2"
runner = "1.7.0"
turbine = "1.2.1"
testLogger = "4.0.0"
dependencyAnalysis = "3.4.1"
dependencyVersions = "0.53.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconExtended" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-test-core = { module = "androidx.test:core", version.ref = "core" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidHilt" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitAndroid" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref= "androidHilt" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
commons-csv = { module = "org.apache.commons:commons-csv", version.ref = "commonsCsv" }
retrofit-converter = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
android-core-testing = { module = "android.arch.core:core-testing", version.ref = "coreTesting" }
fit = { module = "com.garmin:fit", version.ref = "fit" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
java-jwt = { module = "com.auth0:java-jwt", version.ref = "javaJwt" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver3-junit4", version.ref = "okhttp" }
okhttp-signpost = { module = "se.akerfeldt:okhttp-signpost", version.ref = "okhttpSignpost" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-tls = { module = "com.squareup.okhttp3:okhttp-tls", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-room = { id = "androidx.room", version.ref = "roomVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinPlugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinPlugin" }
kotlin-serializable = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinPlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
test-logger = { id = "com.adarshr.test-logger", version.ref = "testLogger"}
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
dependency-versions = { id = "com.github.ben-manes.versions", version.ref = "dependencyVersions" }

